namespace KkomaKnight.Game
{
    /// <summary>GPT로 생성한 효과별 특전 그림. 등급 차이는 카드 프레임과 설명이 나타낸다.</summary>
    public static class PerkArtwork
    {
        public static string Key(string id)
        {
            switch (id)
            {
                case "p_evadeHeal":
                case "p_evHealR":
                case "p_evHealL":
                case "p_evHeal":
                    return "perk.evHeal";
                case "p_atk":
                case "p_atkR":
                    return "perk.atk";
                case "p_evade":
                case "p_evadeR":
                    return "perk.evade";
                case "p_arrowEv":
                case "p_arrowEvR":
                case "p_arrowEvL":
                    return "perk.arrowEv";
                case "p_axeHit":
                case "p_axeHitR":
                case "p_axeHitL":
                    return "perk.axeHit";
                case "p_counter":
                case "p_counterR":
                    return "perk.counter";
                case "p_spearCt":
                    return "perk.spearCt";
                case "p_critR":
                case "p_critRR":
                    return "perk.critR";
                case "p_critF":
                case "p_critFR":
                    return "perk.critF";
                case "p_def":
                case "p_defR":
                case "p_defL":
                    return "perk.def";
                case "p_killSpearN":
                case "p_killSpearR":
                case "p_killSpearL":
                case "p_killSpear":
                    return "perk.killSpear";
                case "p_killBoltN":
                case "p_killBoltR":
                case "p_killBoltL":
                case "p_killBolt":
                    return "perk.killBolt";
                case "p_killArrowN":
                case "p_killArrowR":
                case "p_killArrowL":
                case "p_killArrow":
                    return "perk.killArrow";
                case "p_killAxeN":
                case "p_killAxeR":
                case "p_killAxeL":
                case "p_killAxe":
                    return "perk.killAxe";
                case "p_thornsN":
                case "p_thornsR":
                case "p_thornsL":
                case "p_thorns":
                    return "perk.thorns";
                case "p_killEvBuff":
                    return "perk.killEvBuff";
                case "p_collAtk":
                    return "perk.collAtk";
                case "p_collCrit":
                    return "perk.collCrit";
                case "p_killAtkStk":
                    return "perk.killAtkStk";
                case "p_killEvStk":
                    return "perk.killEvStk";
                case "p_killHealN":
                case "p_killHeal":
                    return "perk.killHeal";
                case "p_collHp":
                    return "perk.collHp";
                case "p_critStack":
                    return "perk.critStack";
                case "p_aspdAtk":
                    return "perk.aspdAtk";
                case "p_execEvN":
                case "p_execEvR":
                case "p_execEvL":
                case "p_execEv":
                    return "perk.execEv";
                case "p_stunCritN":
                case "p_stunCritR":
                case "p_stunCritL":
                case "p_stunCrit":
                    return "perk.stunCrit";
                case "p_nArrowN":
                case "p_nArrowR":
                case "p_nArrowL":
                case "p_nArrow":
                    return "perk.nArrow";
                case "p_nAxeN":
                case "p_nAxeR":
                case "p_nAxeL":
                case "p_nAxe":
                    return "perk.nAxe";
                case "p_nBoltN":
                case "p_nBoltR":
                case "p_nBoltL":
                case "p_nBolt":
                    return "perk.nBolt";
                case "p_nHealN":
                case "p_nHeal":
                    return "perk.nHeal";
                case "p_evadeStun":
                    return "perk.evadeStun";
                case "p_ctCritN":
                case "p_ctCritR":
                case "p_ctCrit":
                    return "perk.ctCrit";
                case "p_ctDmgN":
                case "p_ctDmgR":
                case "p_ctDmg":
                    return "perk.ctDmg";
                case "p_killSureCrit":
                    return "perk.killSureCrit";
                case "p_cleaveN":
                case "p_cleaveR":
                case "p_cleaveL":
                case "p_cleave":
                    return "perk.cleave";
                case "p_ignoreN":
                case "p_ignore":
                    return "perk.ignore";
                case "p_noShAtk":
                    return "perk.noShAtk";
                case "p_noShAspd":
                    return "perk.noShAspd";
                case "p_wardHitN":
                case "p_wardHitR":
                case "p_wardHitL":
                case "p_wardHit":
                    return "perk.wardHit";
                case "p_fullHp":
                    return "perk.fullHp";
                case "p_repairUp":
                    return "perk.repairUp";
                case "p_healUp":
                    return "perk.healUp";
                case "p_healRepair":
                    return "perk.healRepair";
                case "p_killRepair":
                    return "perk.killRepair";
                case "p_killDash":
                    return "perk.killDash";
                case "p_berserkStk":
                    return "perk.berserkStk";
                case "p_evRepairR":
                case "p_evRepairL":
                case "p_evRepair":
                    return "perk.evRepair";
                case "p_critSpearR":
                case "p_critSpearL":
                case "p_critSpear":
                    return "perk.critSpear";
                case "p_overkill":
                    return "perk.overkill";
                case "p_berserk":
                    return "perk.berserk";
                case "p_nobleEye":
                    return "perk.nobleEye";
                case "p_spearAvatar":
                    return "perk.spearAvatar";
                case "p_giant":
                    return "perk.giant";
                case "p_nSpearL":
                case "p_nSpear":
                    return "perk.nSpear";
                case "p_critBoltL":
                case "p_critBolt":
                    return "perk.critBolt";
                case "p_spearEvL":
                case "p_spearEv":
                    return "perk.spearEv";
                case "p_spearHitL":
                case "p_spearHit":
                    return "perk.spearHit";
                case "p_shWallL":
                case "p_shWall":
                    return "perk.shWall";
                case "p_shRefL":
                case "p_shRef":
                    return "perk.shRef";
                default: return null;
            }
        }
    }
}
