#!/usr/bin/env python3
"""Layer Lab «2D Minimal-Environment» 데모 씬 4종(DemoScene_Autumn/DeepForest/Forest/Desert)의 구성을 그대로 읽어
Assets/Scripts/Game/MapLayouts.cs(정적 표) 로 굽고, 쓰인 스프라이트를 catalog.json 에 env.<theme>.<Sprite> 키로 넣는다.
주인 지시(2026-09-05): «그 씬 배치가 맘에 들어서 그대로 복사해도 된다» · (2026-09-06 · T19) «맵 디자인을 데모 씬에 있는 거 그대로».
 - 소품·물결 경계(Road_up)는 전부 **인스턴스 그대로**(x·y·sx·sy · 부모 그룹의 위치·스케일까지 합성) 한 표에 넣는다 — Road_up 은 씬에서
   «Road_Up»(y +1.17) · «Road_Down»(y −1.97) 두 그룹 아래 같은 스프라이트(반전 없음)로 길 위·아래 양쪽에 깔려 있고, Desert 는 그룹 스케일 x 2.9189 로 늘려져 있다.
 - 바닥(Field)·길(Road)은 씬의 인스턴스 값(y · 스케일)을 상수로 굽는다(BattleWorld 가 같은 스케일로 가로 반복).
 - 반복 주기(Width)는 소품 폭을 Road_up 피치의 배수로 올림 → 물결 경계가 이음새 없이 이어진다.
사용: python3 tools/gen_maps.py   (그 뒤 gen_catalog.py 를 돌린다)
"""
import json, os, re, collections, math
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
ENV = os.path.join(ROOT, 'Assets', 'Layer Lab', '2D Minimal-Environment')
SCENES = collections.OrderedDict([('autumn', 'DemoScene_Autumn'), ('deepForest', 'DemoScene_DeepForest'), ('forest', 'DemoScene_Forest'), ('desert', 'DemoScene_Desert')])
SKIP = {'SampleCharacter'}

def guid_map():
    g2p = {}
    for dp, dn, fn in os.walk(ENV):
        for f in fn:
            if f.endswith('.meta'):
                p = os.path.join(dp, f)
                m = re.search(r'guid: ([0-9a-f]{32})', open(p, encoding='utf-8', errors='ignore').read())
                if m: g2p[m.group(1)] = p[:-5]
    return g2p

def prefab_sprite(pp, g2p):
    t = open(pp, encoding='utf-8', errors='ignore').read()
    m = re.search(r'm_Sprite: \{fileID: \d+, guid: ([0-9a-f]{32})', t)
    return g2p.get(m.group(1)) if m else None

def parse(scene_path, g2p):
    """씬의 PrefabInstance 전부 → (스프라이트, 월드 x, y, sx, sy, 프리팹 기본 이름). 부모 트랜스폼 체인의 위치·스케일을 합성한다(회전은 씬에 없음)."""
    t = open(scene_path, encoding='utf-8', errors='ignore').read()
    tr = {}   # 트랜스폼 fileID → (pos, scale, parent)
    for m in re.finditer(r'--- !u!4 &(\d+)\nTransform:\n(.*?)(?=\n--- !u!)', t, re.S):
        b = m.group(2)
        pos = re.search(r'm_LocalPosition: \{x: (-?[\d.e-]+), y: (-?[\d.e-]+)', b)
        sc = re.search(r'm_LocalScale: \{x: (-?[\d.e-]+), y: (-?[\d.e-]+)', b)
        par = re.search(r'm_Father: \{fileID: (\d+)\}', b)
        tr[m.group(1)] = ((float(pos.group(1)), float(pos.group(2))), (float(sc.group(1)), float(sc.group(2))), par.group(1) if par else '0')
    def compose(x, y, sx, sy, par):
        depth = 0
        while par in tr and depth < 16:
            (px, py), (psx, psy), par = tr[par]
            x, y, sx, sy = px + x * psx, py + y * psy, sx * psx, sy * psy
            depth += 1
        return x, y, sx, sy
    rows = []
    for b in t.split('--- !u!')[1:]:
        if not b.startswith('1001 '): continue
        g = re.search(r'm_SourcePrefab: \{fileID: \d+, guid: ([0-9a-f]{32})', b)
        if not g: continue
        pp = g2p.get(g.group(1))
        if not pp: continue
        name = os.path.basename(pp)[:-7]
        base = re.sub(r'_(Autumn|DeepForest|Forest|Desert)$', '', name)
        if base in SKIP or base.startswith('SampleCharacter'): continue
        def val(k, d=None):
            m = re.search(r'propertyPath: ' + re.escape(k) + r'\n\s+value: (-?[\d.e-]+)', b)
            return float(m.group(1)) if m else d
        x, y = val('m_LocalPosition.x', 0.0), val('m_LocalPosition.y', 0.0)
        sx, sy = val('m_LocalScale.x', 1.0), val('m_LocalScale.y', 1.0)
        par = re.search(r'm_TransformParent: \{fileID: (\d+)\}', b)
        x, y, sx, sy = compose(x, y, sx, sy, par.group(1) if par else '0')
        sp = prefab_sprite(pp, g2p)
        if not sp: continue
        rows.append((os.path.basename(sp)[:-4], round(x, 3), round(y, 3), round(sx, 4), round(sy, 4), base))
    return rows

def cap(theme): return theme[0].upper() + theme[1:]
def keyof(theme, r):
    """카탈로그 키 — 물결 경계는 기존 env.<theme>.roadUp · 바닥/길은 env.<theme>.field/road(이미 있는 키를 그대로 쓴다) · 소품은 env.<theme>.<스프라이트 이름>."""
    if r[5].startswith('Road_up'): return f'env.{theme}.roadUp'
    if r[5] == 'Field': return f'env.{theme}.field'
    if r[5] == 'Road': return f'env.{theme}.road'
    return f'env.{theme}.{r[0]}'

def main():
    g2p = guid_map()
    cat_path = os.path.join(ROOT, 'Assets', 'KkomaKnight', 'catalog.json')
    cat = json.load(open(cat_path, encoding='utf-8'), object_pairs_hook=collections.OrderedDict)
    S, N = cat['sprites'], cat['_notes']
    for k in [k for k in S if re.match(r'env\.(autumn|deepForest|forest|desert)\.(deco|big|mid|small)\d+$', k)]:
        S.pop(k); N.pop(k, None)
    sprite_path = {}
    for dp, dn, fn in os.walk(os.path.join(ENV, 'Environment 1', 'ResourcesData', 'Sprites')):
        for f in fn:
            if f.endswith('.png'): sprite_path[f[:-4]] = os.path.relpath(os.path.join(dp, f), ROOT)
    out = ['// <auto-generated> tools/gen_maps.py — Layer Lab Environment 데모 씬 4종의 구성(바닥·길·물결 경계·소품 · 위치·반전·크기 그대로). 손으로 고치지 말고 스크립트를 다시 돌린다.',
           'namespace KkomaKnight.Game', '{',
           '    /// <summary>데모 씬 배치 표 — x/y 는 씬 유니티 단위(길 중심 y = RoadY) · Sx 음수 = 좌우 반전 · 부모 그룹의 위치·스케일은 합성된 값. 씬 폭(Width)마다 반복해 깐다(BattleWorld 가 전체를 <c>Layout.MapScale</c> 배로 그린다 · T19).</summary>',
           '    public static class MapLayouts', '    {',
           '        public struct P { public string Key; public float X, Y, Sx, Sy; public P(string k, float x, float y, float sx, float sy) { Key = k; X = x; Y = y; Sx = sx; Sy = sy; } }']
    field = road = None
    per_theme = collections.OrderedDict()
    for theme, scene in SCENES.items():
        rows = parse(os.path.join(ENV, 'Environment 1', 'Scene', scene + '.unity'), g2p)
        fields = [r for r in rows if r[5] == 'Field']; roads = [r for r in rows if r[5] == 'Road']
        assert len(fields) == 1 and len(roads) == 1, (theme, len(fields), len(roads))
        f, rd = fields[0], roads[0]
        if field is None: field, road = f, rd
        assert (f[2], f[3], f[4]) == (field[2], field[3], field[4]) and (rd[2], rd[3], rd[4]) == (road[2], road[3], road[4]), ('씬마다 Field/Road 값이 다르다', theme)
        props = [r for r in rows if r[5] not in ('Field', 'Road')]
        ups = [r for r in props if r[5].startswith('Road_up')]
        xs = [r[1] for r in props if not r[5].startswith('Road_up')]
        prop_width = max(xs) - min(xs) + 3.0                      # 소품 폭 + 여백
        # 물결 경계는 행(위 y ≈ +1.13 · 아래 y ≈ −2.0)마다 따로 — DeepForest/Forest 는 두 행이 반 피치 어긋나 있어 x 를 섞어 세면 피치가 반으로 틀린다
        rows_by_y = collections.OrderedDict()
        for r in sorted(ups, key=lambda r: (r[2], r[1])): rows_by_y.setdefault(r[2], []).append(r)
        pitches = [(row[-1][1] - row[0][1]) / (len(row) - 1) for row in rows_by_y.values() if len(row) > 1]
        pitch = sum(pitches) / len(pitches) if pitches else prop_width
        n_up = max(len(row) for row in rows_by_y.values()) if rows_by_y else 0
        m = max(n_up, int(math.ceil(prop_width / pitch - 1e-6)))
        width = round(m * pitch, 3)
        for row in rows_by_y.values():   # 행이 m 칸보다 짧으면 같은 피치로 이어 붙여 이음새 없이(현 4씬은 전부 행 길이 == m)
            ref = row[-1]
            for i in range(len(row), m): props.append((ref[0], round(row[0][1] + i * pitch, 3), ref[2], ref[3], ref[4], ref[5]))
        for r in props + [f, rd]:
            key = keyof(theme, r)
            if key not in S: S[key] = sprite_path[r[0]]
            assert S[key] == sprite_path[r[0]], ('카탈로그 키가 다른 그림을 가리킨다', key, S[key], sprite_path[r[0]])
        first_prop = sorted(props, key=lambda r: r[1])[0]
        N[keyof(theme, first_prop)] = f'«{scene}» 소품 — tools/gen_maps.py 가 씬 구성(소품·물결 경계 Road_up 위·아래 · 바닥·길)을 그대로 MapLayouts.cs 로 굽는다 (이 테마 스프라이트 {len(set(r[0] for r in props))}종 · 인스턴스 {len(props)}개)'
        per_theme[theme] = (props, width, f, rd, n_up, pitch, m)
        print(theme, 'props', len(props), '(Road_up', len(ups), '· 행', len(rows_by_y), '· 행 피치', round(pitch, 3), '· 행당', n_up, ')', 'prop width', round(prop_width, 2), '→ period', width, '=', m, '× pitch', '· x range', min(xs), max(xs))
    out.append(f'        /// <summary>바닥(Field_*) 인스턴스 — y {field[2]} · 스케일 x {field[3]} · y {field[4]} (128px 스프라이트 → {round(1.28 * field[3], 2)} × {round(1.28 * field[4], 2)}u 평면 · 씬마다 같다).</summary>')
    out.append(f'        public const float FieldY = {field[2]}f, FieldScaleX = {field[3]}f, FieldScaleY = {field[4]}f;')
    out.append(f'        /// <summary>길(Road_*) 인스턴스 — y {road[2]} · 스케일 x {road[3]} · y {road[4]} (128px 스프라이트 → {round(1.28 * road[3], 2)} × {round(1.28 * road[4], 2)}u 띠 · 씬마다 같다). 물결 경계(Road_up)는 표 안에 소품과 똑같이 들어 있다(위 y ≈ +1.13 · 아래 y ≈ −2.0).</summary>')
    out.append(f'        public const float RoadCenterY = {road[2]}f, RoadScaleX = {road[3]}f, RoadScaleY = {road[4]}f;')
    for theme, (props, width, f, rd, n_up, pitch, m) in per_theme.items():
        out.append(f'        /// <summary>{SCENES[theme]} — 반복 주기 {width}u = Road_up 피치 {round(pitch, 3)} × {m} · 바닥 키 <c>{keyof(theme, f)}</c> · 길 키 <c>{keyof(theme, rd)}</c>.</summary>')
        out.append(f'        public const float {cap(theme)}Width = {width}f;')
        out.append(f'        public const string {cap(theme)}Field = "{keyof(theme, f)}", {cap(theme)}Road = "{keyof(theme, rd)}";')
        out.append(f'        public static readonly P[] {cap(theme)} =')
        out.append('        {')
        for r in sorted(props, key=lambda r: (r[1], r[2])):
            out.append(f'            new P("{keyof(theme, r)}", {r[1]}f, {r[2]}f, {r[3]}f, {r[4]}f),')
        out.append('        };')
    def sw(name, ret, expr):
        cases = ' '.join(f'case "{th}": return {expr(cap(th))};' for th in list(SCENES)[:-1])
        return f'        public static {ret} {name}(string theme) {{ switch (theme) {{ {cases} default: return {expr(cap(list(SCENES)[-1]))}; }} }}'
    out.append('        /// <summary>테마 이름(autumn·deepForest·forest·desert) → 표 · 반복 주기 · 바닥/길 카탈로그 키.</summary>')
    out.append(sw('Of', 'P[]', lambda c: c))
    out.append(sw('WidthOf', 'float', lambda c: c + 'Width'))
    out.append(sw('FieldOf', 'string', lambda c: c + 'Field'))
    out.append(sw('RoadOf', 'string', lambda c: c + 'Road'))
    out += ['    }', '}', '']
    open(os.path.join(ROOT, 'Assets', 'Scripts', 'Game', 'MapLayouts.cs'), 'w', encoding='utf-8').write('\n'.join(out))
    json.dump(cat, open(cat_path, 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(cat_path, 'a', encoding='utf-8').write('\n')
    print('wrote MapLayouts.cs · sprites', len(S))

if __name__ == '__main__':
    main()
