#!/usr/bin/env python3
"""Layer Lab «2D Minimal-Environment» 데모 씬 4종(DemoScene_Autumn/DeepForest/Forest/Desert)의 소품 배치를 그대로 읽어
Assets/Scripts/Game/MapLayouts.cs(정적 표) 로 굽고, 쓰인 스프라이트를 catalog.json 에 env.<theme>.<Sprite> 키로 넣는다.
주인 지시(2026-09-05): «그 씬 배치가 맘에 들어서 그대로 복사해도 된다» — 위치·반전·크기를 씬 값 그대로 쓴다(바닥 Field/Road 와 샘플 캐릭터는 제외 · Road_up 은 따로 길 전체에 깐다).
사용: python3 tools/gen_maps.py   (그 뒤 gen_catalog.py 를 돌린다)
"""
import json, os, re, collections
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
ENV = os.path.join(ROOT, 'Assets', 'Layer Lab', '2D Minimal-Environment')
SCENES = collections.OrderedDict([('autumn', 'DemoScene_Autumn'), ('deepForest', 'DemoScene_DeepForest'), ('forest', 'DemoScene_Forest'), ('desert', 'DemoScene_Desert')])
SKIP = {'Field', 'Road', 'SampleCharacter'}

def guid_map():
    g2p = {}
    for dp, dn, fn in os.walk(ENV):
        for f in fn:
            if f.endswith('.meta'):
                p = os.path.join(dp, f)
                m = re.search(r'guid: ([0-9a-f]{32})', open(p, encoding='utf-8', errors='ignore').read())
                if m: g2p[m.group(1)] = p[:-5]
    return g2p

def prefab_sprite(pp, g2p):
    t = open(pp, encoding='utf-8', errors='ignore').read()
    m = re.search(r'm_Sprite: \{fileID: \d+, guid: ([0-9a-f]{32})', t)
    return g2p.get(m.group(1)) if m else None

def parse(scene_path, g2p):
    t = open(scene_path, encoding='utf-8', errors='ignore').read()
    # 트랜스폼 fileID → localPosition (부모 오프셋 확인용)
    tpos = {}
    for m in re.finditer(r'--- !u!4 &(\d+)\nTransform:.*?m_LocalPosition: \{x: (-?[\d.e-]+), y: (-?[\d.e-]+)', t, re.S):
        tpos[m.group(1)] = (float(m.group(2)), float(m.group(3)))
    rows = []
    for b in t.split('--- !u!')[1:]:
        if not b.startswith('1001 '): continue
        g = re.search(r'm_SourcePrefab: \{fileID: \d+, guid: ([0-9a-f]{32})', b)
        if not g: continue
        pp = g2p.get(g.group(1))
        if not pp: continue
        name = os.path.basename(pp)[:-7]
        base = re.sub(r'_(Autumn|DeepForest|Forest|Desert)$', '', name)
        if base in SKIP or base.startswith('SampleCharacter'): continue
        def val(k, d=None):
            m = re.search(r'propertyPath: ' + re.escape(k) + r'\n\s+value: (-?[\d.e-]+)', b)
            return float(m.group(1)) if m else d
        x, y = val('m_LocalPosition.x', 0.0), val('m_LocalPosition.y', 0.0)
        sx, sy = val('m_LocalScale.x', 1.0), val('m_LocalScale.y', 1.0)
        par = re.search(r'm_TransformParent: \{fileID: (\d+)\}', b)
        if par and par.group(1) in tpos:
            px, py = tpos[par.group(1)]; x += px; y += py
        sp = prefab_sprite(pp, g2p)
        if not sp: continue
        rows.append((os.path.basename(sp)[:-4], round(x, 3), round(y, 3), round(sx, 3), round(sy, 3), base.startswith('Road_up')))
    return rows

def main():
    g2p = guid_map()
    cat_path = os.path.join(ROOT, 'Assets', 'KkomaKnight', 'catalog.json')
    cat = json.load(open(cat_path, encoding='utf-8'), object_pairs_hook=collections.OrderedDict)
    S, N = cat['sprites'], cat['_notes']
    # 이전 세대 키(deco/big/mid/small) 제거
    for k in [k for k in S if re.match(r'env\.(autumn|deepForest|forest|desert)\.(deco|big|mid|small)\d+$', k)]:
        S.pop(k); N.pop(k, None)
    sprite_path = {}
    for dp, dn, fn in os.walk(os.path.join(ENV, 'Environment 1', 'ResourcesData', 'Sprites')):
        for f in fn:
            if f.endswith('.png'): sprite_path[f[:-4]] = os.path.relpath(os.path.join(dp, f), ROOT)
    out = ['// <auto-generated> tools/gen_maps.py — Layer Lab Environment 데모 씬 4종의 소품 배치(위치·반전·크기 그대로). 손으로 고치지 말고 스크립트를 다시 돌린다.',
           'namespace KkomaKnight.Game', '{',
           '    /// <summary>데모 씬 배치 표 — x/y 는 씬 유니티 단위(길 중심 y = -0.402) · Sx 음수 = 좌우 반전. 씬 폭(Width)마다 반복해 깐다.</summary>',
           '    public static class MapLayouts', '    {',
           '        public struct P { public string Key; public float X, Y, Sx, Sy; public P(string k, float x, float y, float sx, float sy) { Key = k; X = x; Y = y; Sx = sx; Sy = sy; } }',
           '        public const float RoadCenterY = -0.402f, RoadHeight = 2.4624f;   // Road_* 인스턴스: y -0.402 · 세로 스케일 2.4624 (128px 스프라이트 → 2.46u)']
    for theme, scene in SCENES.items():
        rows = parse(os.path.join(ENV, 'Environment 1', 'Scene', scene + '.unity'), g2p)
        props = [r for r in rows if not r[5]]; ups = [r for r in rows if r[5]]
        xs = [r[1] for r in props]
        width = round(max(xs) - min(xs) + 3.0, 2)     # 씬 폭 + 여백 → 반복 주기
        up_pitch = round((max(r[1] for r in ups) - min(r[1] for r in ups)) / max(1, len(ups) - 1), 3) if len(ups) > 1 else 1.19
        up_y = ups[0][2] if ups else -0.036
        for r in props:
            key = f'env.{theme}.{r[0]}'
            if key not in S:
                S[key] = sprite_path[r[0]]
        N[f'env.{theme}.{props[0][0]}'] = f'«{scene}» 소품 — tools/gen_maps.py 가 씬 배치를 그대로 MapLayouts.cs 로 굽는다 (이 테마 소품 {len(set(r[0] for r in props))}종 · 인스턴스 {len(props)}개)'
        out.append(f'        public static readonly float {(theme[0].upper() + theme[1:])}Width = {width}f, {(theme[0].upper() + theme[1:])}RoadUpPitch = {up_pitch}f, {(theme[0].upper() + theme[1:])}RoadUpY = {up_y}f;')
        out.append(f'        public static readonly P[] {(theme[0].upper() + theme[1:])} =')
        out.append('        {')
        for r in sorted(props, key=lambda r: r[1]):
            out.append(f'            new P("env.{theme}.{r[0]}", {r[1]}f, {r[2]}f, {r[3]}f, {r[4]}f),')
        out.append('        };')
        print(theme, 'props', len(props), 'width', width, 'roadUp pitch', up_pitch, 'y', up_y, 'x range', min(xs), max(xs))
    out.append('        public static P[] Of(string theme) { switch (theme) { case "autumn": return Autumn; case "deepForest": return DeepForest; case "forest": return Forest; default: return Desert; } }')
    out.append('        public static float WidthOf(string theme) { switch (theme) { case "autumn": return AutumnWidth; case "deepForest": return DeepForestWidth; case "forest": return ForestWidth; default: return DesertWidth; } }')
    out.append('        public static float RoadUpPitchOf(string theme) { switch (theme) { case "autumn": return AutumnRoadUpPitch; case "deepForest": return DeepForestRoadUpPitch; case "forest": return ForestRoadUpPitch; default: return DesertRoadUpPitch; } }')
    out.append('        public static float RoadUpYOf(string theme) { switch (theme) { case "autumn": return AutumnRoadUpY; case "deepForest": return DeepForestRoadUpY; case "forest": return ForestRoadUpY; default: return DesertRoadUpY; } }')
    out += ['    }', '}', '']
    open(os.path.join(ROOT, 'Assets', 'Scripts', 'Game', 'MapLayouts.cs'), 'w', encoding='utf-8').write('\n'.join(out))
    json.dump(cat, open(cat_path, 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(cat_path, 'a', encoding='utf-8').write('\n')
    print('wrote MapLayouts.cs · sprites', len(S))

if __name__ == '__main__':
    main()
